name: Merge Master to Staging

on:
  push:
    branches:
      - master  # Define que será disparado no push para a branch prod

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        ref: master  # Verifica o código da branch prod

    - name: Configure git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    - name: Merge prod into stg
      run: |
        git checkout staging
        git merge master
        git push origin staging  # Faz o push da stg após o merge
