name: Merge Master To Staging

on:
  push:
    branches:
      - master  # Dispara o workflow quando houver um push na branch master

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Create a Pull Request
      id: create_pr
      run: |
        # Verifica se j치 h치 um PR aberto da master para staging
        pr_url=$(gh pr list --base staging --head master --json url -q '.[].url')
        if [ -z "$pr_url" ]; then
          # Cria um novo PR da master para staging
          gh pr create --head master --base staging --title "Merge master into staging" --body "Automatically created PR to sync master with staging."
        else
          echo "PR j치 existe: $pr_url"
        fi

    - name: Merge the Pull Request
      run: |
        pr_url=$(gh pr list --base staging --head master --json url -q '.[].url')
        if [ -n "$pr_url" ]; then
          # Faz o merge autom치tico do PR
          gh pr merge "$pr_url" --auto --delete-branch
        else
          echo "Nenhum PR encontrado para merge."
        fi

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
