#name: Update Staging Branch
#
#on:
#  push:
#    branches:
#      - master
#
#jobs:
#  update-staging:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#      - name: Backup Staging Branch
#        run: |
#          git fetch origin
#          git checkout origin/staging
#          git branch staging-backup
#          git push origin staging-backup
#      - name: Delete Staging Branch
#        run: |
#          git push origin :staging
#      - name: Create New Staging Branch
#        run: |
#          git checkout -b staging origin/master
#          git push origin staging